In [2]:
import pandas as pd

C:\Users\gustavo.yath\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
df = pd.DataFrame({
    'CATEGORIA': ['A', 'B', 'A', 'B', 'A'],
    'VENDAS': [100, 200, 150, 300, 120],
    'QUANTIDADE': [1, 2, 1, 3, 2]
})
df

  CATEGORIA  VENDAS  QUANTIDADE
0         A     100           1
1         B     200           2
2         A     150           1
3         B     300           3
4         A     120           2

In [ ]:
# Agrupa por categoria e faz a média

df.groupby('CATEGORIA')['VENDAS'].describe()

           count        mean        std    min    25%    50%    75%    max
CATEGORIA
A            3.0  123.333333  25.166115  100.0  110.0  120.0  135.0  150.0
B            2.0  250.000000  70.710678  200.0  225.0  250.0  275.0  300.0

In [ ]:
# Agrupa por categoria e faz a média

df.groupby('CATEGORIA')['QUANTIDADE'].describe()

           count      mean       std  min   25%  50%   75%  max
CATEGORIA
A            3.0  1.333333  0.577350  1.0  1.00  1.0  1.50  2.0
B            2.0  2.500000  0.707107  2.0  2.25  2.5  2.75  3.0

In [ ]:
# Soma por categoria (apenas colunas numéricas)

df.groupby('CATEGORIA').sum()

           VENDAS  QUANTIDADE
CATEGORIA
A             370           4
B             500           5

In [17]:
# Agrupa por múltiplas colunas

df.groupby(['CATEGORIA', 'QUANTIDADE'], as_index=False)['VENDAS'].sum()

  CATEGORIA  QUANTIDADE  VENDAS
0         A           1     250
1         A           2     120
2         B           2     200
3         B           3     300