In [ ]:
# Exercicio: Criar um DataFrame e filtrar por salario maior que 3000, e outro por vendedor e vendedora
import pandas as pd

C:\Users\gustavo.yath\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
dic = {
    'NOME': ['Geronimo', 'Martha', 'Patroclos', 'Tiberios', 'Janaina', 'Mercedes'],
    'CARGO': ['Gerente', 'Gerente', 'Vendedor', 'Secretario', 'Vendedora', 'Vendedor'],
    'SALARIO': [9600.56, 9600.56, 2600.90, 4500.45, 2600.90, 2600.90]
}

df = pd.DataFrame(dic)
df

        NOME       CARGO  SALARIO
0   Geronimo     Gerente  9600.56
1     Martha     Gerente  9600.56
2  Patroclos    Vendedor  2600.90
3   Tiberios  Secretario  4500.45
4    Janaina   Vendedora  2600.90
5   Mercedes    Vendedor  2600.90

In [3]:
df[df['SALARIO'] >= 3000.00]

       NOME       CARGO  SALARIO
0  Geronimo     Gerente  9600.56
1    Martha     Gerente  9600.56
3  Tiberios  Secretario  4500.45

In [4]:
df[df['CARGO'].isin(['Vendedor', 'Vendedora'])]

        NOME      CARGO  SALARIO
2  Patroclos   Vendedor   2600.9
4    Janaina  Vendedora   2600.9
5   Mercedes   Vendedor   2600.9