In [1]:
import pandas as pd

C:\Users\gustavo.yath\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
dados = {
    'nome': ['patrick', 'marcio', 'fabio', 'thomas', 'sergio'],
    'matricula': [1234567, 7654321, 9856738, 547263, 238756],
    'endereço' : ['rio de janeiro', 'são paulo', 'recife', 'bahia', 'minas gerais']
}

df = pd.DataFrame(dados)

In [3]:
df.head(3)

      nome  matricula        endereço
0  patrick    1234567  rio de janeiro
1   marcio    7654321       são paulo
2    fabio    9856738          recife

In [4]:
df.tail(3)

     nome  matricula      endereço
2   fabio    9856738        recife
3  thomas     547263         bahia
4  sergio     238756  minas gerais