In [1]:
import pandas as pd

C:\Users\gustavo.yath\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
dados = {
    'cargos': ["assistente", "auxiliar", "gerente"],
    'salários': [2500, 1800, 7500],
}

In [12]:
dados_bi = pd.DataFrame(dados)
dados_bi

       cargos  salários
0  assistente      2500
1    auxiliar      1800
2     gerente      7500

In [13]:
dados_bi.head(2)

       cargos  salários
0  assistente      2500
1    auxiliar      1800

In [14]:
dados_bi.tail(1)

    cargos  salários
2  gerente      7500

In [15]:
dados_bi.shape

(3, 2)

In [16]:
dados_bi.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cargos    3 non-null      str
 1   salários  3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 205.0 bytes

In [17]:
dados_bi.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cargos    3 non-null      str
 1   salários  3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 205.0 bytes

In [18]:
dados_bi.describe()

          salários
count     3.000000
mean   3933.333333
std    3108.590249
min    1800.000000
25%    2150.000000
50%    2500.000000
75%    5000.000000
max    7500.000000

In [24]:
dados_bi.iloc[1]

cargos      auxiliar
salários        1800
Name: 1, dtype: object