In [1]:
import pandas as pd

C:\Users\gustavo.yath\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
dados = {
    'categoria': ['Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos',
                  'Roupas', 'Roupas', 'Roupas', 'Roupas',
                  'Alimentos', 'Alimentos', 'Alimentos', 'Alimentos'],
    'ano':       [2022, 2022, 2023, 2023,
                  2022, 2022, 2023, 2023,
                  2022, 2022, 2023, 2023],
    'vendas':    [1000, 1500, 2000, 2500,
                  800,  900,  1100, 1300,
                  500,  600,  700,  850]
}

df = pd.DataFrame(dados)
df

      categoria   ano  vendas
0   Eletrônicos  2022    1000
1   Eletrônicos  2022    1500
2   Eletrônicos  2023    2000
3   Eletrônicos  2023    2500
4        Roupas  2022     800
5        Roupas  2022     900
6        Roupas  2023    1100
7        Roupas  2023    1300
8     Alimentos  2022     500
9     Alimentos  2022     600
10    Alimentos  2023     700
11    Alimentos  2023     850

In [4]:
tabela_pivot = df.pivot_table(
    index='categoria', # Define a coluna que será usada como linha e tabela
    columns='ano', # Define a coluna que será usada como coluna tabela
    values='vendas', # Coluna cujos valores serão agregados
    aggfunc='sum' # Função de agregação
)
tabela_pivot

ano          2022  2023
categoria
Alimentos    1100  1550
Eletrônicos  2500  4500
Roupas       1700  2400